# Generated by Django 6.0.3 on 2026-03-16 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "org_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
        migrations.AddField(
            model_name="patient",
            name="is_deceased",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField(blank=True, null=True)),
                ("stop", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("reason_code", models.CharField(blank=True, max_length=50)),
                ("reason_description", models.CharField(blank=True, max_length=255)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="patients.patient",
                        to_field="patient_id",
                    ),
                ),
            ],
            options={
                "ordering": ["-start"],
            },
        ),
    ]
