# Generated by Django 6.0.3 on 2026-03-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0002_organization_remove_patient_age_patient_is_deceased_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="cohort",
            field=models.CharField(
                choices=[
                    ("chronic", "Chronic Disease"),
                    ("at_risk", "At Risk"),
                    ("pediatric", "Pediatric"),
                    ("deceased", "Deceased"),
                ],
                db_index=True,
                default="chronic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="code",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="observation",
            name="date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="is_deceased",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
